CREATE OR REPLACE TABLE load_data.public.sample_orders_cli ( 
    ORDER_ID NUMBER(38, 0), 
    TRUCK_ID NUMBER(38, 0), 
    LOCATION_ID NUMBER(38, 0), 
    CUSTOMER_ID NUMBER(38, 0), 
    DISCOUNT_ID VARCHAR, 
    SHIFT_ID NUMBER(38, 0), 
    SHIFT_START_TIME TIME, 
    SHIFT_END_TIME TIME, 
    ORDER_CHANNEL VARCHAR, 
    ORDER_TS TIMESTAMP_NTZ, 
    SERVED_TS VARCHAR, 
    ORDER_CURRENCY VARCHAR, 
    ORDER_AMOUNT NUMBER(38, 4), 
    ORDER_TAX_AMOUNT VARCHAR, 
    ORDER_DISCOUNT_AMOUNT VARCHAR, 
    ORDER_TOTAL NUMBER(38, 4) 
); 

CREATE OR REPLACE FILE FORMAT load_data.public.file_format_cli
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO load_data.public.sample_orders_cli
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
	FROM @snowflake_cli_stage)
FILES = ('sample_orders.csv') 
FILE_FORMAT = ( FORMAT_NAME='load_data.public.file_format_cli')
ON_ERROR=ABORT_STATEMENT 